#!/bin/bash
#SBATCH --job-name=centrifuge
#SBATCH --account=da494
#SBATCH --partition=compute
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=04:00:00
#SBATCH --output=centrifuge_%j.out

module load centrifuge

cd /storage/aelangov/raw_practice_data/fastp_res
mkdir -p /storage/aelangov/raw_practice_data/centrifuge_res

for file in *_trimmed_1.fastq.gz; do
  sample=$(basename "$file" _trimmed_1.fastq.gz)

  centrifuge \
    -x /storage/shared/centrifuge_db/p_compressed \
    -1 ${sample}_trimmed_1.fastq.gz \
    -2 ${sample}_trimmed_2.fastq.gz \
    --report-file /storage/aelangov/centrifuge_res/${sample}_report.tsv \
    -S /storage/aelangov/centrifuge_res/${sample}.classified.tsv \
    -p 4
done
