#!/bin/sh
#SBATCH --job-name=centrifuge_blanks
#SBATCH --account=da494
#SBATCH --partition=compute
#SBATCH --cpus-per-task=4
#SBATCH --time=02:00:00
#SBATCH --mem=16G
#SBATCH --output=centrifuge_blanks_%j.out

module load centrifuge

mkdir -p /storage/aelangov/actual_samples/decontamination_samples/roman_blank/raw_reads
mkdir -p /storage/aelangov/actual_samples/decontamination_samples/viking_blank/raw_reads
mkdir -p /storage/aelangov/actual_samples/decontamination_samples/centrifuge_blank_reports

cd /storage/aelangov/actual_samples/decontamination_samples/roman_blank/raw_reads
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR132/006/ERR1329876/ERR1329876_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR132/006/ERR1329876/ERR1329876_2.fastq.gz

cd /storage/aelangov/actual_samples/decontamination_samples/viking_blank/raw_reads
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR132/007/ERR1329877/ERR1329877_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR132/007/ERR1329877/ERR1329877_2.fastq.gz

DB=/storage02/data/centrifuge-dbs/park-et-al-2020/hpvc
OUT=/storage/aelangov/actual_samples/decontamination_samples/centrifuge_blank_reports

centrifuge -p $SLURM_CPUS_PER_TASK -x $DB \
-1 /storage/aelangov/actual_samples/decontamination_samples/roman_blank/raw_reads/ERR1329876_1.fastq.gz \
-2 /storage/aelangov/actual_samples/decontamination_samples/roman_blank/raw_reads/ERR1329876_2.fastq.gz \
-S $OUT/roman_blank_centrifugeOutputs.txt \
--report-file $OUT/roman_blank_centrifugeReport.txt

centrifuge -p $SLURM_CPUS_PER_TASK -x $DB \
-1 /storage/aelangov/actual_samples/decontamination_samples/viking_blank/raw_reads/ERR1329877_1.fastq.gz \
-2 /storage/aelangov/actual_samples/decontamination_samples/viking_blank/raw_reads/ERR1329877_2.fastq.gz \
-S $OUT/viking_blank_centrifugeOutputs.txt \
--report-file $OUT/viking_blank_centrifugeReport.txt
