#!/bin/bash
#SBATCH --job-name=multiqc_all
#SBATCH --account=da494
#SBATCH --partition=compute
#SBATCH --cpus-per-task=2
#SBATCH --mem=4G
#SBATCH --time=01:00:00
#SBATCH --output=multiqc_all_%j.out

module load bioconda
conda activate qc_env

# Create output folder
mkdir -p /storage/aelangov/actual_samples/multiqc_all_samples

#  Roman Samples (Normal)
multiqc \
  /storage/aelangov/actual_samples/roman_samples/*/raw_reads/calculus/fastqc_res \
  --force \
  -o /storage/aelangov/actual_samples/multiqc_all_samples

#  Viking/Anglo Samples (Normal)
multiqc \
  /storage/aelangov/actual_samples/anglo_viking_samples/*/raw_reads/calculus/fastqc_res \
  --force \
  -o /storage/aelangov/actual_samples/multiqc_all_samples

# Add Bone sample (only ERR1407510)
multiqc \
  /storage/aelangov/actual_samples/error_fastp_res/fastqc_res/ERR1407510* \
  --force \
  -o /storage/aelangov/actual_samples/multiqc_all_samples

#  Add Norton-on-Tees fixed samples
multiqc \
  /storage/aelangov/actual_samples/final_error_trimmed/fastqc_res \
  --force \
  -o /storage/aelangov/actual_samples/multiqc_all_samples

echo " MultiQC completed for ALL samples (normal + fixed error samples)"
