#!/bin/bash
#SBATCH --job-name=multiqc_all
#SBATCH --account=da494
#SBATCH --partition=compute
#SBATCH --cpus-per-task=2
#SBATCH --mem=4G
#SBATCH --time=01:00:00
#SBATCH --output=multiqc_all_%j.out

# Load conda environment
module load bioconda
conda activate qc_env

# Create final output folder
mkdir -p /storage/aelangov/actual_samples/multiqc_all_fastqc_res

#  Run MultiQC on ALL sample folders together
multiqc \
  /storage/aelangov/actual_samples/roman_samples/driffield_york/raw_reads/calculus/fastqc_res \
  /storage/aelangov/actual_samples/roman_samples/oxford_leicester/raw_reads/calculus/fastqc_res \
  /storage/aelangov/actual_samples/anglo_viking_samples/norton_on_tees/raw_reads/calculus/fastqc_res \
  /storage/aelangov/actual_samples/anglo_viking_samples/coppergate_york/raw_reads/calculus/fastqc_res \
  /storage/aelangov/actual_samples/error_fastp_res/fastqc_res/ERR1407510* \
  /storage/aelangov/actual_samples/final_error_trimmed/fastqc_res \
  --force \
  -o /storage/aelangov/actual_samples/multiqc_all_fastqc_res

echo "MultiQC report for ALL normal and error-fixed samples"
