#!/bin/bash
#SBATCH --job-name=multiqc_final_manual
#SBATCH --account=da494
#SBATCH --partition=compute
#SBATCH --cpus-per-task=2
#SBATCH --mem=4G
#SBATCH --time=01:00:00
#SBATCH --output=multiqc_final_manual_%j.out

module load bioconda
conda activate qc_env

# Make output folder
mkdir -p /storage/aelangov/actual_samples/multiqc_final_manual

# Run MultiQC on all required folders/files
multiqc \
  /storage/aelangov/actual_samples/roman_samples/driffield_york/raw_reads/calculus/fastqc_res \
  /storage/aelangov/actual_samples/roman_samples/oxford_leicester/raw_reads/calculus/fastqc_res \
  /storage/aelangov/actual_samples/anglo_viking_samples/coppergate_york/raw_reads/calculus/fastqc_res \
  /storage/aelangov/actual_samples/anglo_viking_samples/norton_on_tees/raw_reads/calculus/fastqc_res/ERR1329832*_fastqc.zip \
  /storage/aelangov/actual_samples/anglo_viking_samples/norton_on_tees/raw_reads/calculus/fastqc_res/ERR1329836*_fastqc.zip \
  /storage/aelangov/actual_samples/anglo_viking_samples/norton_on_tees/raw_reads/calculus/fastqc_res/ERR1329838*_fastqc.zip \
  /storage/aelangov/actual_samples/anglo_viking_samples/norton_on_tees/raw_reads/calculus/fastqc_res/ERR1329851*_fastqc.zip \
  /storage/aelangov/actual_samples/error_fastp_res/fastqc_res/ERR1407510_clean_* \
  /storage/aelangov/actual_samples/final_error_trimmed/fastqc_res/ERR1329841_final_* \
  /storage/aelangov/actual_samples/final_error_trimmed/fastqc_res/ERR1329847_final_* \
  --force \
  -o /storage/aelangov/actual_samples/multiqc_final_manual

echo " MultiQC completed (manual paths, old error samples excluded)"
