#!/bin/bash
#SBATCH --job-name=multiqc
#SBATCH --account=da494
#SBATCH --partition=compute
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH --time=00:30:00
#SBATCH --output=multiqc_%j.out

# Load conda and activate it
module load bioconda
conda activate qc_env

# Go to the home folder where the fastqc and fastp are stored
cd /storage/aelangov/raw_practice_data

# Running MultiQC on everything inside this folder
multiqc . -o multiqc_report
