#!/bin/bash
#SBATCH --job-name=fastqc_all
#SBATCH --account=da494
#SBATCH --partition=compute
#SBATCH --cpus-per-task=2
#SBATCH --mem=4G
#SBATCH --time=02:00:00
#SBATCH --output=fastqc_all_%j.out

# Load conda environment
module load bioconda
conda activate qc_env

#  ROMAN - Oxford Leicester - Calculus
cd /storage/aelangov/actual_samples/roman_samples/oxford_leicester/raw_reads/calculus
mkdir -p fastqc_res
fastqc *.fastq.gz --threads 2 --outdir fastqc_res

#  ROMAN - Oxford Leicester - Bone
cd /storage/aelangov/actual_samples/roman_samples/oxford_leicester/raw_reads/Bone
mkdir -p fastqc_res
fastqc *.fastq.gz --threads 2 --outdir fastqc_res

# ROMAN - Driffield York
cd /storage/aelangov/actual_samples/roman_samples/driffield_york/raw_reads/calculus
mkdir -p fastqc_res
fastqc *.fastq.gz --threads 2 --outdir fastqc_res

# VIKING anglo - Coppergate York
cd /storage/aelangov/actual_samples/anglo_viking_samples/coppergate_york/raw_reads/calculus
mkdir -p fastqc_res
fastqc *.fastq.gz --threads 2 --outdir fastqc_res

#  VIKING anglo- Norton-on-Tees
cd /storage/aelangov/actual_samples/anglo_viking_samples/norton_on_tees/raw_reads/calculus
mkdir -p fastqc_res
fastqc *.fastq.gz --threads 2 --outdir fastqc_res

echo " FastQC complete for all samples"
